### ISSUE TITLE
Does not work on Windows, exception

### ISSUE THREAD

**Issue by Bestora** [albertz/RandomFtpGrabber#1]
```
root dir: C:\Users\Dennis\Desktop\RandomFtpGrabber-master
EXCEPTION
Traceback (most recent call last):
  File "C:\Users\Dennis\Desktop\RandomFtpGrabber-master\main.py", line 31, in <m
odule>
    line: import TaskSystem # important to be initially imported in the main thr
ead
    locals:
      TaskSystem = <not found>
  File "C:\Users\Dennis\Desktop\RandomFtpGrabber-master\TaskSystem.py", line 3,
in <module>
    line: from queue import Queue
    locals:
      queue = <not found>
      Queue = <not found>
ImportError: No module named queue
```

**Comment by albertz** [comment]
What Python version is that?

**Comment by Bestora** [comment]
Latest on python page for Windows. I'll look it up later
Am 28.12.2014 22:56 schrieb "Albert Zeyer" notifications@github.com:

**Comment by Bestora** [comment]
Python 2.7.9 - 2014-12-10

**Comment by albertz** [comment]
This is for Python 3. Can you try with Python 3?
